x = int(1)
print(type(x))
print(x)
x = int(2.5)
print(type(x))
print(x)
x = float(36.46)
print(type(x))
print(x)
x = str("SEX")
print(type(x))
print(x)
x = "Hello"
y = "World"
z = str(x) + str(y)
print(z)
x = 46.82
print("The vaule of variable x is "+str(x)+" respectively.")
s = "World_Wide_Web"
print(s)
print(s[4])
print(s[3:6])
print(s.strip())
s = 'ALL Right Reserved'
print(s.strip())
print("The length of variable \"s\" is: "+str(len(s))+" characters.")
print(s.lower())
print(s.upper())
print(s.replace("ALL","Jelly"))
print(s.split(" "))
